Use condense_control()
tidymodels/tune pull request #540
Opened 2022-09-15 00:54 UTC by EmilHvitfeldt

This PR reflects the changes made in https://github.com/tidymodels/parsnip/pull/808.

This means that we get more flexibility in cases where we need to pass a control object from function to function.

``` r
library(tidymodels)

rec_no_tune_1 <-
  recipe(mpg ~ ., data = mtcars) %>%
  step_normalize(all_predictors())

mt_folds <- vfold_cv(mtcars, v = 5)

tree_mod_no_tune <- decision_tree(min_n = 3) %>% 
  set_mode("regression") %>%
  set_engine("rpart")

tree_wf_no_tune <- workflow() %>%
  add_recipe(rec_no_tune_1) %>%
  add_model(tree_mod_no_tune)

# fit_resamples
tree_wf_no_tune %>%
  fit_resamples(mt_folds, control = control_bayes())
#> # Resampling results
#> # 5-fold cross-validation 
#> # A tibble: 5 × 4
#>   splits         id    .metrics         .notes          
#>   <list>         <chr> <list>           <list>          
#> 1 <split [25/7]> Fold1 <tibble [2 × 4]> <tibble [0 × 3]>
#> 2 <split [25/7]> Fold2 <tibble [2 × 4]> <tibble [0 × 3]>
#> 3 <split [26/6]> Fold3 <tibble [2 × 4]> <tibble [0 × 3]>
#> 4 <split [26/6]> Fold4 <tibble [2 × 4]> <tibble [0 × 3]>
#> 5 <split [26/6]> Fold5 <tibble [2 × 4]> <tibble [0 × 3]>
```

<sup>Created on 2022-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2022-09-15 17:39 UTC, EmilHvitfeldt commented
As far as I can tell, the CI errors are fixed in https://github.com/tidymodels/tune/pull/541

2022-09-15 17:42 UTC, EmilHvitfeldt commented on tests/testthat/test-condense_control.R
> +  ctrl <- parsnip::condense_control(
I'm assume here that `control_grid()` is in theory a super of `control_resamples()`, they just happen to be equal at this point in time

2022-09-20 17:00 UTC, topepo requested changes

2022-09-20 17:00 UTC, topepo commented on NEWS.md
> +* `last_fit()`, `fit_resamples()`, `tune_grid()`, and `tune_bayes()` no longer error if `control` argument isn't a the corresponding `control_*()` object. Will work as long as the object passed to `c
```suggestion
* `last_fit()`, `fit_resamples()`, `tune_grid()`, and `tune_bayes()` do not automatically error if  the wrong type of `control` object is passed. If the passed control object is not a superset of the one that is needed, the function will still error. As an example, passing `control_grid()` to `tune_bayes()` will fail but passing `control_bayes()` to `tune_grid()` will not. ([#449](https://github.com/tidymodels/tune/issues/449))
```

2022-09-20 17:29 UTC, EmilHvitfeldt commented
Changes has been merged :)

2022-09-22 13:26 UTC, merged